### ISSUE TITLE
Milestone 1: User Interface Requirements

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#13]
To provide a description of how the product is supposed to work from the user's perspective

**Comment by chsiang469** [comment]
Completed. Snippet of User Interface Requirements from the report included.

![Image](https://user-images.githubusercontent.com/25312335/191910165-4bc3ee98-6b6f-4a50-ab26-26f8601f9412.PNG)
