### ISSUE TITLE
Milestone 1: Use Case Model (UML Diagram)

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#15]
To draw UML diagram to better understand, alter, maintain, or document information about the system

**Comment by chsiang469** [comment]
Completed. UML can be found at:
https://lucid.app/lucidchart/070b480a-0a84-439e-8128-31421acfce07/edit?viewport_loc=-11%2C-11%2C1579%2C868%2C0_0&invitationId=inv_ee628e71-ebc2-4631-9858-e9acb4aca9a6
