### ISSUE TITLE
Milestone 1: Gantt Chart

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#20]
Create a Gnatt Chart to track the progress of the project.

**Comment by Meh1** [comment]
Gnatt Chart is viewable on [https://sitsingaporetechedu-my.sharepoint.com/:x:/g/personal/1802945_sit_singaporetech_edu_sg/EUGFQcnpVC9JrRRHGZwRW28Bk4pOGoDBDY8hF4YMd6iuZA?e=MnimOs](https://sitsingaporetechedu-my.sharepoint.com/:x:/g/personal/1802945_sit_singaporetech_edu_sg/EUGFQcnpVC9JrRRHGZwRW28Bk4pOGoDBDY8hF4YMd6iuZA?e=MnimOs)
