### ISSUE TITLE
Milestone 1: Other Requirements

### ISSUE THREAD

**Issue by Meh1** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#24]
Any other requirements that are pertinent to the project. (Optional)

**Comment by angpeihao98** [comment]
Other requirements include PDPA

**Comment by chsiang469** [comment]
Completed. Snippet of Other Requirements from the report included.


![Image](https://user-images.githubusercontent.com/25312335/192082968-877aec17-279b-4cdc-82cf-45b155d26397.PNG)
