### ISSUE TITLE
Milestone 3: White Box Testing

### ISSUE THREAD

**Issue by chsiang469** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#30]
To test the software structures, design, flow and security of the product

**Comment by angpeihao98** [comment]
Team decided on doing the white box testing on the indicate availability method.

**Comment by chsiang469** [comment]
We aimed to complete White Box Testing by 24 November.

**Comment by chsiang469** [comment]
Completed. Attached is a small portion of the White Box Testing in our report.



![Image](https://user-images.githubusercontent.com/25312335/204091863-71244417-dbb8-45c4-9a69-a13dc362dcab.png)
