### ISSUE TITLE
Milestone 1 Retrospective: What could be improved 1

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#39]
We can split the bigger tasks into smaller manageable sections.

**Comment by chsiang469** [comment]
Our team chose to split each individual portion of the report into smaller sections, with each member taking a section for every header in the report. This allowed us to closely work together to ensure that every section flows properly to the next.



![Image](https://user-images.githubusercontent.com/25312335/198817906-9b50aa84-5059-41b0-8d4e-8901f465e3f1.png)
