### ISSUE TITLE
Milestone 2: Architectural Design

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#44]
Describe the software architectural design and complement with diagrams such as component diagrams

**Comment by chsiang469** [comment]
Aim to complete by 25 September 2022

**Comment by chsiang469** [comment]
Software architectural description completed, subject to last min changes if necessary.

![Image](https://user-images.githubusercontent.com/25312335/197712253-bd6911bc-df1a-474f-981e-2e0dadd7b2b6.png)



Completed component diagram

![Image](https://user-images.githubusercontent.com/25312335/197712691-9467c458-2326-480d-a76c-18de2872e1c1.png)
