### ISSUE TITLE
Milestone 2: Detailed Design

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#45]
Describe software classes and use parts of class diagram to explain. Sequence diagram can be used to explain design flow between objects

**Comment by chsiang469** [comment]
Aim to complete by 28 September 2022

**Comment by chsiang469** [comment]
Completed. Snippet of detailed design can be found below



![Image](https://user-images.githubusercontent.com/25312335/198817716-fc1996cd-4ae3-4545-9207-b174959d38ec.png)
