### ISSUE TITLE
Milestone 2: Project Plan

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#46]
To calculate the resources required and overall time required for the project. Status of project, work allocations and any overruns should be included

**Comment by chsiang469** [comment]
Aim to complete by 29 September 2022

**Comment by chsiang469** [comment]
Completed. Snippet of Project plan from report included.



![Image](https://user-images.githubusercontent.com/25312335/198817877-1de5e14e-0f1b-4e6b-ac47-ffdcf7fca315.png)
