### ISSUE TITLE
Milestone 2: Sequence Diagram

### ISSUE THREAD

**Issue by chsiang469** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#48]
Sequence Diagram to explain the flow between objects

**Comment by chsiang469** [comment]
Aim to complete by 26 October 2022

**Comment by Meh1** [comment]
[ICT2201 UML Diagram - Sequence Diagram.pdf](https://github.com/ICT2201-p1-3/ICT2x01-Team-Project_p1-3/files/9893150/ICT2201.UML.Diagram.-.Sequence.Diagram.pdf)

Sequence Diagrams completed

**Comment by Meh1** [comment]
![Image](https://user-images.githubusercontent.com/19339470/198817584-0ada2a34-c26c-4717-9518-c1ae9c6e0a67.png)

UC01 - CreateNew Accounts
