### ISSUE TITLE
Milestone 2: Implement feedback from Milestone 1

### ISSUE THREAD

**Issue by abiphone** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#49]
To implement an updated UCD and description based on feedback from milestone 1

**Comment by chsiang469** [comment]
All updates have been clarified through email or during lab sessions, and any changes made since milestone 1 was written in specific requirements.



![Image](https://user-images.githubusercontent.com/25312335/198838823-fce49b06-8bc6-46ce-8677-b03f6cd12a0e.png)
