### ISSUE TITLE
Questions to clarify with client

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#50]
Questions needed to clarify with the client which will be sent through email.

**Comment by angpeihao98** [comment]
Clarify the updated user interface requirements for milestone 2.

**Comment by angpeihao98** [comment]
The SC comment in milestone 1 report.

**Comment by abiphone** [comment]
To check if excel should be an entity since it's internal.

**Comment by angpeihao98** [comment]
![Image](https://user-images.githubusercontent.com/48192384/197322619-e4ae6c54-c3e2-4aa0-a99b-fc33b8e4cdf5.png)

**Comment by angpeihao98** [comment]
Milestone 2 report -> project plan -> resources required

Don't quite understand what is needed here. The resources refer to hardware resources (web server specs/computer specs) or software resources (web server version/database version) or both?

**Comment by angpeihao98** [comment]
![Image](https://user-images.githubusercontent.com/48192384/197969783-079d5ebb-721c-449e-9c41-752c413a191b.jpg)
