### ISSUE TITLE
Milestone 2 Retrospective: What will we commit to improve in the next milestone?

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#51]
We will improve our communications and make sure that everyone in the team is aware when there is a change in the diagrams that were drawn during the earlier stages of the report.

**Comment by chsiang469** [comment]
Milestone 3 review:

we chose to update everyone whenever we made a change to the diagram, and had extensive discussions so that everyone would be aware of the change.


![Image](https://user-images.githubusercontent.com/25312335/204091406-155b7105-1b8b-4c0c-8e27-fa6b9ddd1b46.png)
