### ISSUE TITLE
Milestone 2 Retrospective: What could be improved?

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#52]
The communication among the team could be further improved because we did not communicate when making changes to the diagram which leads to inconsistencies in the report.

**Comment by chsiang469** [comment]
Milestone 3 review:

This round, we discussed what needed to be done for each portion of the diagram, such as the login diagram, making sure that we covered the necessary portions and not do any tasks that were not related. We also took this approach for each portion of the report




![Image](https://user-images.githubusercontent.com/25312335/204091518-fd75968a-294d-4936-8183-ce9d94d91259.png)
