### ISSUE TITLE
Milestone 3: Prototype Video

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#53]
A short 3 minute video, narrated and captioned which walks through prototype and addresses requirements

**Comment by chsiang469** [comment]
We aimed to complete the video by 24 November

**Comment by chsiang469** [comment]
Video shared to team members for comments on 25 November



![Image](https://user-images.githubusercontent.com/25312335/204091916-3aa40d29-d8b8-489d-8131-e2687f22af1a.png)
