### ISSUE TITLE
Milestone 3: Team Management

### ISSUE THREAD

**Issue by angpeihao98** [ICT2201-p1-3/ICT2x01-Team-Project_p1-3#54]
Project Management Portion

**Comment by chsiang469** [comment]
We aimed to complete Project Management by 23 November

**Comment by chsiang469** [comment]
Completed, Attached is a portion of the Project Management from our report.




![Image](https://user-images.githubusercontent.com/25312335/204091960-ff5e0ccd-619d-4e46-91c6-c47c87b7bdaf.png)
